C CE FICHIER PERMET DE RENDRE LA GLOBALE LA VISIBILITE DES VARIABLES DECLAREES CI-DESSOUS
C POUR UTILISER CES VARIABLES DANS VOS SUBROUTINES OU FONCTIONS, IL FAUT AJOUTER LA
C COMMANDE       INCLUDE 'common.inc' APRES LA COMMANDE IMPLICIT NONE

C-----------------------------------------------------------------------------------------------------------------------
C LES CONSTANTES (C)
      INTEGER N
      DOUBLE PRECISION C 
C-----------------------------------------------------------------------------------------------------------------------
C#######################################################################################################################
C#######################################################################################################################
C LES COMMONS
      COMMON/C1/N
      COMMON/C2/C

